apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-pipeline-demo
  template:
    metadata:
      labels:
        app: cicd-pipeline-demo
    spec:
      containers:
      - name: cicd-pipeline-demo
        image: rexbrown20/cicd-pipeline-demo:latest
        ports:
        - containerPort: 3000

