apiVersion: v1
kind: Service
metadata:
  name: cicd-pipeline-service
spec:
  selector:
    app: cicd-pipeline-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
